### ISSUE TITLE
datecmp 기반 기술 조사

### ISSUE THREAD

**Issue by YEONGORI** [YEONGORI/Project2#12]
struct tm 구조체에는 년, 월, 일, 시, 분, 초 등의 시간 정보가 저장됩니다. 따라서 localtime() 함수를 사용하여 st_mtime 값을 struct tm 구조체로 변환한 후, 시간 정보를 비교하면 됩니다.

**Comment by Icecoff22** [comment]
기술이 너무 간단한 것 같습니다

**Comment by sangpyeong** [comment]
열심히 해보아요
